### ISSUE TITLE
Upgrade to react-side-effect v1.0

### ISSUE THREAD

**Issue by erikras** [kodyl/react-document-meta#1]
Some breaking, but ultimately superior, changes in [v1.0](https://github.com/gaearon/react-side-effect/releases/tag/v1.0.0).

**Comment by danieljuhl** [comment]
Sure, I'll look into this as soon as possible, but probably not before next week. PR welcome.

**Comment by erikras** [comment]
[Looks pretty easy.](https://github.com/gaearon/react-document-title/commit/75ef9566a162a4c9bc697c0e23cf5c44ac5efb74)

**Comment by danieljuhl** [comment]
@erikras it's now done and released to npm as v1.0.0, with a few breaking changes to use with server rendering.

**Comment by erikras** [comment]
:+1: Thanks!
