### ISSUE TITLE
DocumentMeta renders previous request data

### ISSUE THREAD

**Issue by leticia** [kodyl/react-document-meta#12]
Hi!

I'm using React + Redux + server side rendering and react-document-data to display og tags. When opening two different pages, the second one seems to be rendered with the first page tags.

I declare docMeta as seen in [this](https://github.com/kodyl/react-document-meta/blob/master/example/index.js) example.

The problem is seen in this gif: 

![share](https://cloud.githubusercontent.com/assets/35051/11448239/6a9efa3a-953b-11e5-9aff-eec59e2b5462.gif)

Initially, both pages are rendered with correct meta tags. When I reload "something" and go to "save-the-whales" tab and reload it, meta tags from "something" are displayed.

Is there something I'm missing on setting up react-document-meta?

**Comment by danieljuhl** [comment]
When you use server side renderinger, you have to "extract" the content after you render on the server, and then inject the extracted data into you final HTML before serving to the client. The content in react-document-meta is generated when React renders the components.

**Comment by danieljuhl** [comment]
It's your lucky day. I'll commit a server-side rendering example in a few hours - just cleaning up.

**Comment by leticia** [comment]
Thank you, @danieljuhl!

**Comment by nicolasiensen** [comment]
Hey @danieljuhl, what if my HTML is being rendered by a React component like [this](https://github.com/meurio/hub-client/blob/115853b6c04cddff977426b0e2c599e744e8abc1/src/Html.js)?

**Comment by danieljuhl** [comment]
@nicolasiensen simply call React.renderToString and assign to a variable before returning the HTML.
```
  render() {
    const {assets, component, store} = this.props
    const content = React.renderToString(component);
    return (
      <html lang="en-us">
        <head>
          <meta charSet="utf-8"/>
          {DocumentMeta.renderAsReact()}
          <link rel="shortcut icon" href="/favicon.ico" />

          {/* styles (will be present only in production with webpack extract text plugin) */}
          {Object.keys(assets.styles).map((style, i) =>
            <link href={assets.styles[style]} key={i} media="screen, projection"
                  rel="stylesheet" type="text/css"/>
          )}
          <script dangerouslySetInnerHTML={{__html: analytics}} />
        </head>
        <body>
          <div id="content" dangerouslySetInnerHTML={{__html: content}}/>
          <script src="/wysihtml/wysihtml-toolbar.min.js" />
          <script src="/wysihtml/advanced_and_extended.js" />
          <script dangerouslySetInnerHTML={{__html: `window.__data=${serialize(store.getState())};`}} />
          <script src={assets.javascript.main}/>
        </body>
      </html>
    )
  }
```

**Comment by nicolasiensen** [comment]
![Clever!](http://www.thetoddanderinfavoritefive.com/wp/wp-content/uploads/2013/09/clever-ideas-to-make-life-easier-520x390.jpg)
