### ISSUE TITLE
provide some real life examples

### ISSUE THREAD

**Issue by varandpez** [kodyl/react-document-meta#18]
While updating readme , could you please show how can client side implementation be used in real world? with og tags is there anyway to test them to see its working?

Thanks.

**Comment by danieljuhl** [comment]
@varandpez what do you mean, when saying "real world" examples? Have you looked in `example` folder?

**Comment by varandpez** [comment]
So here what I meant....
I used this and populated og tags on client side, everything's fine and values are in header and I can verify that in HTML.

Then I used "ngrok" and opened a tunnel from localhost to outside world. 
Then using "http://opengraphcheck.com/" website I tried to test the results. It doesn't see the newly populated values. Just returns the whatever was in HEAD before react-document-meta puts the new values.

I'm about to test server side example. Hope it solves this issue.

**Comment by danieljuhl** [comment]
You will need to use server-side rendering, if you want the tags to be present in the initial HTML. That's kind of the concept of server-side rendering :)

Unless the "parser" (in this case opengraphcheck.com) evaluates JS, which I don't think, the tags won't be shown.

Bottomline, you'll need to use the server-side rendering example, for you case.
