### ISSUE TITLE
React 15.0 support?

### ISSUE THREAD

**Issue by sompylasar** [kodyl/react-document-meta#20]
It's already RC2: https://facebook.github.io/react/blog/2016/03/16/react-v15-rc2.html

**Comment by tadjik1** [comment]
plz update dependencies list for react v15

**Comment by danieljuhl** [comment]
It should be a pure dependency definition issue. I haven't encountered any problems with React 15.0 in my initial testing. I've updated package.json in master, and will make a release tomorrow.
