### ISSUE TITLE
Suppress `data-rdm` attributes?

### ISSUE THREAD

**Issue by mpelzsherman** [kodyl/react-document-meta#29]
Is there an option to suppress the `data-rdm` attributes added to each tag?

What is the purpose of these attributes?

(Thanks!)

**Comment by danieljuhl** [comment]
Currently no - but I do see the idea in removing, especially for server side rendering to static pages.

The reason to add `data-rdm` is that the `<head>` is manipulated outside of the `react` scope, so  we need some way to be able to detect that they have been created using `react-document-meta` when the user navigates, and we need to create new meta tags in the `<head>`.

**Comment by mpelzsherman** [comment]
Thanks @danieljuhl. It's not a huge problem for us. Might be worth mentioning in the README though.

**Comment by danieljuhl** [comment]
Sure! 👍
