### ISSUE TITLE
Remove 'react' and 'react-dom' from dependencies

### ISSUE THREAD

**Issue by necolas** [kodyl/react-document-meta#31]
This package's `dependencies` is causing npm/yarn to install React(DOM)@0.14. Would suggest either removing them as `dependencies` or setting `peerDependencies` that includes >1.0

**Comment by danieljuhl** [comment]
I'll make a new version tomorrow morning CET, fixing this.

**Comment by danieljuhl** [comment]
@necolas I just tried to re-produce, and I don't see this behaviour with `npm`. Will make a test with `yarn`. Also, I have no problem moving the `react` and `react-dom` to `peerDependencies`, but shouldn't `15.4.x` be satisfied with semver `>=0.14.0`?

**Comment by danieljuhl** [comment]
`react-document-meta@2.1.1` has been released

**Comment by danieljuhl** [comment]
One could argue that it should have been semver major, but as `react-document-meta`can't be used without `react`, as did see this as a simple patch fix, to avoid multiple versions of `react`
