### ISSUE TITLE
Server Rendering: DocumentMeta.renderAsHTML() is not a function

### ISSUE THREAD

**Issue by therayess** [kodyl/react-document-meta#32]
Hi,

Trying to use this plugin, while i'm applying the server rendering code as described in the provided documentation, i keep getting this error: DocumentMeta.renderAsHTML() is not a function, same when i use renderAsReact().

Any idea?

Thanks

**Comment by therayess** [comment]
It's weird too because even without the server rendering, i set the title and canonical tags individually in my pages and those are updated accordingly, but for metas like keywords they don't update, so i guess server rendering is a must, but how are the title and canonical being updated successfully then?? just wondering..

**Comment by danieljuhl** [comment]
@therayess I would need some more information. Which version of react, react-document-meta, code samples, etc. - bottom line, the module is used in many of our projects, without problems. And if you follow the examples in the this repo, everything works fine. It looks like you are having problems with your module system (require/import/etc).

**Comment by therayess** [comment]
"react": "^15.3.1",
 "react-document-meta": "^2.0.3"

code sample:
index.js
-------
const DocumentMeta = require('react-document-meta');

const meta = DocumentMeta.renderAsHTML();

it breaks at that line ^

**Comment by danieljuhl** [comment]
This is not a complete sample. Just two lines of code. If you want my help, you need to share more. And why don't you use the latest version?

**Comment by danieljuhl** [comment]
Please provide a fill reproducible sample including the full error and stack trace. As said the samples work just fine and lots of people are using this module without problems. It's seems like you are doing something I can't see from you comments.

**Comment by therayess** [comment]
thanks for ur feedback Daniel, i updated the plugin and its now working, should've done so from the beginning, my bad -_- thanks again!
