### ISSUE TITLE
Use the prop-types package from npm instead of Accessing PropTypes via the main React package

### ISSUE THREAD

**Issue by davidep87** [kodyl/react-document-meta#35]
Since the latest React update over the version 15.5.* i get this warning.
Warning: Accessing PropTypes via the main React package is deprecated. 

Use the prop-types package from npm instead of Accessing PropTypes via the main React package

**Comment by danieljuhl** [comment]
@davidep87 which version of `react-document-meta` are you using?

**Comment by davidep87** [comment]
i got the version 2.1.1

**Comment by danieljuhl** [comment]
`v2.1.2` is the latest, please update
