### ISSUE TITLE
adding script tag

### ISSUE THREAD

**Issue by A-Kasaaian** [kodyl/react-document-meta#40]
I want to add script tag  with "src" for loading external js files depend on the active component.
I tried:
`const meta={
    script:{src: "/path/to/example.js"}
}`
not working at all. Please, provide an example for this case and also an example for stylesheet link tag.

**Comment by danieljuhl** [comment]
This is not currently possible, but something we're working on for v3 which will be releases this month

**Comment by danieljuhl** [comment]
Stylesheets can be added using:
`<DocumentMeta meta={{ link: { rel: { stylesheet: ["../style.css"] } } }} />`

**Comment by SQReder** [comment]
@A-Kasaaian What is the case to load some external libs? Why don't use lasy loading modules?

**Comment by A-Kasaaian** [comment]
Yea, Thanks
