### ISSUE TITLE
Title is getting set as an empty string

### ISSUE THREAD

**Issue by casschin** [kodyl/react-document-meta#41]
I'm using this library to add some <link /> tags to a page and I noticed that my page title was being set to an empty string, even though I was using the `extend` prop. 

I got around this by setting the title again when rendering the `<DocumentMeta />` component with this meta object:

```javascript
const meta = {
    title: document.title,
    link: {
        ...
    }
}
```

I was looking at the source code and saw [this line](https://github.com/kodyl/react-document-meta/blob/master/lib/index.js#L41). Is there a reason why it sets the title to an empty string?

**Comment by danieljuhl** [comment]
Just one quick question... you are setting the document title initially during SSR, and then you don't have any title (besides the workaround) in your client-side code, correct?

**Comment by danieljuhl** [comment]
@casschin this has been published in v3 beta
