### ISSUE TITLE
google sees the page without meta tags

### ISSUE THREAD

**Issue by romanown** [kodyl/react-document-meta#45]
at first glance, everything works well and in the code in the browser you can see meta tags. but when you view the page code there is nothing. and google sees the page without meta tags. I use the module on the product catalog page. all data is transferred. I can see everything in the reaction tools. but Google doesn't see it. after I start using this component, almost all pages are removed from the Google cache. I have 
`"react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",`
`"_id": "react-document-meta@3.0.0-beta.2"`

**Comment by danieljuhl** [comment]
@romanown did you remember to include the meta data during server side rendering? https://github.com/kodyl/react-document-meta#server-usage

We have several apps/websites using this without problems.

**Comment by romanown** [comment]
thank You. should I only do it on the server? or on the client side as it is necessary to do as shown in the example above server example?
`const meta = DocumentMeta.renderAsHTML();` is not have any arguments and props?

**Comment by romanown** [comment]
I did it in a file on the server. but received an error.
`You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: _reactDocumentMeta2.default.renderAsHTML is not a function`

**Comment by romanown** [comment]
I have such structure.
![default](https://user-images.githubusercontent.com/7169357/44816759-d8eee800-abeb-11e8-9553-9bc39c47886c.png)
node starts the server. app accesses the server as a proxy and receives data.

**Comment by danieljuhl** [comment]
@romanown it has to be done on the server (as it needs to be part of the initial HTML for Google to be able to see it), and yes, renderAsHTML() has no arguments or props, but has to be called after you React DOM server-side rendering.

Without seeing your full code and knowning your stack, it is hard to debug your issue, but it could be something with the way you import `renderAsHTML`/`react-document-meta`.

Can you provide the code for server.js (mainly where you import react-document-meta and where you use it).

**Comment by romanown** [comment]
thank You. i am changed renderAsHTML to renderAsReact and its working.
