### ISSUE TITLE
How to add custom tag?

### ISSUE THREAD

**Issue by arunaharsa** [kodyl/react-document-meta#6]
for example, i would like to add <link rel="dns-prefetch" href="http://google.com" />
is there any way?

I used 

{
  link: {rel:'dns-prefetch', href='http://google.com'}
}

but it printed into 2 tags instead:
<link rel="dns-prefetch" />
<link href="http://google.com" />

**Comment by arunaharsa** [comment]
ok, found a way
link:{rel:{'dns-prefetch':'http:google.com'}

**Comment by danieljuhl** [comment]
Not a way, you found the way :)
