### ISSUE TITLE
es6 problem ?

### ISSUE THREAD

**Issue by bbnnt** [kodyl/react-document-meta#7]
I'm writing plain es5
Here's what I get with your example : 
![Image of Yaktocat](https://40.media.tumblr.com/879966af168c9f71ff057c998bfbda9c/tumblr_nv121vyDrI1qzp3szo1_1280.png)
Is that the reason ? If it is, still possible to use it with es5 ?

**Comment by danieljuhl** [comment]
Can you please provide your source code?

**Comment by bbnnt** [comment]
Sorry for not posting the code.; let's just closed it I guess the problem was on my side. Ended up with Helmet though, I assume yours works the same

**Comment by danieljuhl** [comment]
That's okay. Helmet works a bit different for nested meta data and merge strategy.
